name: Tests on bash shell

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  bash-tests:
    runs-on: ubuntu-latest
    container:
      image: bash:${{ matrix.bash_version }}

    strategy:
      fail-fast: false
      matrix:
        bash_version: ["3.2", "4.0", "5.2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        id: setup
        run: |
          apk add --no-cache git findutils util-linux coreutils tree

          git clone https://github.com/bats-core/bats-core.git
          ./bats-core/install.sh /usr/local

      - name: Core tests
        if: ${{ steps.setup.outcome == 'success' && always() }}
        run: |
          SHELL_PATH="/usr/local/bin/bash"
          echo "Running with $SHELL_PATH"
          $SHELL_PATH --version
          TEST_SHELL="$SHELL_PATH" bats tests/core

      - name: Integration tests
        if: ${{ steps.setup.outcome == 'success' && always() }}
        run: |
          SHELL_PATH="/usr/local/bin/bash"
          echo "Running with $SHELL_PATH"
          $SHELL_PATH --version
          TEST_SHELL="$SHELL_PATH" bats tests/integration

      - name: Environment variables tests
        if: ${{ steps.setup.outcome == 'success' && always() }}
        run: |
          SHELL_PATH="/usr/local/bin/bash"
          echo "Running with $SHELL_PATH"
          $SHELL_PATH --version
          TEST_SHELL="$SHELL_PATH" bats tests/envvars

      - name: Performance tests
        if: ${{ steps.setup.outcome == 'success' && always() }}
        run: |
          SHELL_PATH="/usr/local/bin/bash"
          echo "Running with $SHELL_PATH"
          $SHELL_PATH --version
          TEST_SHELL="$SHELL_PATH" bats tests/perf
        continue-on-error: true
